spring:
  application:
    name: CartService
  config:
    import: configserver:http://localhost:8082
  datasource:
    url: jdbc:mysql:http://localhost:3306/petshop
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        issuer-uri: https://dev-atfpp36qj24tzo8l.us.auth0.com/

server:
  port: 8086